apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-mongodb
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
      name: mongo
  selector:
    app: {{ include "tradingagents-cn.name" . }}
    component: mongodb
