apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi
