apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-certs
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-certs
          secret:
            secretName: nginx-proxy-tls
            optional: true
