apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location / {
          proxy_pass http://tradingagents-cn-tradingagents-cn-web.default.svc.cluster.local:8501/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location /_stcore/stream {
          proxy_pass http://tradingagents-cn-tradingagents-cn-web.default.svc.cluster.local:8501/_stcore/stream;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 86400;
        }
      }
      error_log /var/log/nginx/error.log debug;
    }
