apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-redis-commander
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis-commander
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redisCommander.port }}
      targetPort: {{ .Values.redisCommander.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis-commander
