apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-redis
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
  selector:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis
