apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-redis
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "tradingagents-cn.name" . }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ include "tradingagents-cn.name" . }}
        component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.redis.port }}
          command: ["redis-server", "--appendonly", "yes", "--requirepass", "{{ .Values.redis.password }}"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "tradingagents-cn.fullname" . }}-redis-pvc
