apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-redis-pvc
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.volumeSize }}
