apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradingagents-cn.fullname" . }}-web
  labels:
    app: {{ include "tradingagents-cn.name" . }}
    component: web
spec:
  type: {{ .Values.web.service.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "tradingagents-cn.name" . }}
    component: web
